class CreateParameters < ActiveRecord::Migration
  def self.up
    unless table_exists? :parameters
      create_table :parameters do |t|
         t.column :ExpoCode, :text 
         t.column :SALNTY     , :text
         t.column :SALNTY_PI  , :text
         t.column :OXYGEN     , :text
         t.column :OXYGEN_PI  , :text
         t.column :SILCAT     , :text
         t.column :SILCAT_PI  , :text
         t.column :NITRAT     , :text
         t.column :NITRAT_PI  , :text
         t.column :NITRIT     , :text
         t.column :NITRIT_PI  , :text
         t.column :PHSPHT     , :text
         t.column :PHSPHT_PI  , :text
         t.column :"CFC-11", :text
         t.column :"CFC-11_PI"  , :text
         t.column :"CFC-12"     , :text
         t.column :"CFC-12_PI"  , :text
         t.column :TRITUM     , :text
         t.column :TRITUM_PI  , :text
         t.column :HELIUM     , :text
         t.column :HELIUM_PI  , :text
         t.column :DELHE3     , :text
         t.column :DELHE3_PI  , :text
         t.column :DELC14     , :text
         t.column :DELC14_PI  , :text
         t.column :DELC13     , :text
         t.column :DELC13_PI  , :text
         t.column :"KR-85"      , :text
         t.column :"KR-85_PI"   , :text
         t.column :ARGON      , :text
         t.column :ARGON_PI   , :text
         t.column :"AR-39"      , :text
         t.column :"AR-39_PI"   , :text
         t.column :NEON       , :text
         t.column :NEON_PI    , :text
         t.column :"RA-228"     , :text
         t.column :"RA-228_PI"  , :text
         t.column :"RA-226"     , :text
         t.column :"RA-226_PI"  , :text
         t.column :"O18/O16"    , :text
         t.column :"O18/O16_PI" , :text
         t.column :"SR-90"      , :text
         t.column :"SR-90_PI"   , :text
         t.column :"CS-137"     , :text
         t.column :"CS-137_PI"  , :text
         t.column :TCARBN     , :text
         t.column :TCARBN_PI  , :text
         t.column :ALKALI     , :text
         t.column :ALKALI_PI  , :text
         t.column :PCO2       , :text
         t.column :PCO2_PI    , :text
         t.column :PH         , :text
         t.column :PH_PI      , :text
         t.column :CFC113     , :text
         t.column :CFC113_PI  , :text
         t.column :CCL4       , :text
         t.column :CCL4_PI    , :text
         t.column :IODATE     , :text
         t.column :IODATE_PI  , :text
         t.column :IODIDE     , :text
         t.column :IODIDE_PI  , :text
         t.column :NH4        , :text
         t.column :NH4_PI     , :text
         t.column :CH4        , :text
         t.column :CH4_PI     , :text
         t.column :DON        , :text
         t.column :DON_PI     , :text
         t.column :N2O        , :text
         t.column :N2O_PI     , :text
         t.column :CHLORA     , :text
         t.column :CHLORA_PI  , :text
         t.column :PPHYTN     , :text
         t.column :PPHYTN_PI  , :text
         t.column :DMS        , :text
         t.column :DMS_PI     , :text
         t.column :BARIUM     , :text
         t.column :BARIUM_PI  , :text
         t.column :POC        , :text
         t.column :POC_PI     , :text
         t.column :PON        , :text
         t.column :PON_PI     , :text
         t.column :BACT       , :text
         t.column :BACT_PI    , :text
         t.column :DOC        , :text
         t.column :DOC_PI     , :text
         t.column :COMON      , :text
         t.column :COMON_PI   , :text
         t.column :C13ERR     , :text
         t.column :C13ERR_PI  , :text
         t.column :C14ERR     , :text
         t.column :C14ERR_PI  , :text
         t.column :BTLNBR     , :text
         t.column :BTLNBR_PI  , :text
         t.column :CASTNO     , :text
         t.column :CASTNO_PI  , :text
         t.column :CTDOXY     , :text
         t.column :CTDOXY_PI  , :text
         t.column :CTDPRS     , :text
         t.column :CTDPRS_PI  , :text
         t.column :CTDRAW     , :text
         t.column :CTDRAW_PI  , :text
         t.column :CTDSAL     , :text
         t.column :CTDSAL_PI  , :text
         t.column :CTDTMP     , :text
         t.column :CTDTMP_PI  , :text
         t.column :FLUOR      , :text
         t.column :FLUOR_PI   , :text
         t.column :"NO2+NO3"    , :text
         t.column :"NO2+NO3_PI" , :text
         t.column :PCO2TMP    , :text
         t.column :PCO2TMP_PI , :text
         t.column :PHTEMP     , :text
         t.column :PHTEMP_PI  , :text
         t.column :REVPRS     , :text
         t.column :REVPRS_PI  , :text
         t.column :REVTMP     , :text
         t.column :REVTMP_PI  , :text
         t.column :SAMPNO     , :text
         t.column :SAMPNO_PI  , :text
         t.column :STNNBR     , :text
         t.column :STNNBR_PI  , :text
         t.column :TDN        , :text
         t.column :TDN_PI     , :text
         t.column :THETA      , :text
         t.column :THETA_PI   , :text
         t.column :XMISS      , :text
         t.column :XMISS_PI   , :text
         t.column :AOU        , :text
         t.column :AOU_PI     , :text
         t.column :ARAB       , :text
         t.column :ARAB_PI    , :text
         t.column :AZOTE      , :text
         t.column :AZOTE_PI   , :text
         t.column :BRDU       , :text
         t.column :BRDU_PI    , :text
         t.column :CALCIUM    , :text
         t.column :CALCIUM_PI , :text
         t.column :CU         , :text
         t.column :CU_PI      , :text
         t.column :DCNS       , :text
         t.column :DCNS_PI    , :text
         t.column :DELHE4     , :text
         t.column :DELHE4_PI  , :text
         t.column :DELHER     , :text
         t.column :DELHER_PI  , :text
         t.column :DIC        , :text
         t.column :DIC_PI     , :text
         t.column :FUC        , :text
         t.column :FUC_PI     , :text
         t.column :GAL        , :text
         t.column :GAL_PI     , :text
         t.column :GLU        , :text
         t.column :GLU_PI     , :text
         t.column :HELIER     , :text
         t.column :HELIER_PI  , :text
         t.column :"IOD-129"    , :text
         t.column :"IOD-129_PI" , :text
         t.column :MAN        , :text
         t.column :MAN_PI     , :text
         t.column :MCHFRM     , :text
         t.column :MCHFRM_PI  , :text
         t.column :NEONER     , :text
         t.column :NEONER_PI  , :text
         t.column :NI         , :text
         t.column :NI_PI      , :text
         t.column :NO2        , :text
         t.column :NO2_PI     , :text
         t.column :PEUK       , :text
         t.column :PEUK_PI    , :text
         t.column :PRO        , :text
         t.column :PRO_PI     , :text
         t.column :RHAM       , :text
         t.column :RHAM_PI    , :text
         t.column :SF6        , :text
         t.column :SF6_PI     , :text
         t.column :SYN        , :text
         t.column :SYN_PI     , :text
         t.column :TOC        , :text
         t.column :TOC_PI     , :text
         t.column :TRITER     , :text
         t.column :TRITER_PI  , :text
         t.column :CF12ER     , :text
         t.column :CF12ER_PI  , :text
         t.column :PHPUNC     , :text
         t.column :PHPUNC_PI  , :text
         t.column :SILUNC     , :text
         t.column :SILUNC_PI  , :text
         t.column :NRAUNC     , :text
         t.column :NRAUNC_PI  , :text
         t.column :NRIUNC     , :text
         t.column :NRIUNC_PI  , :text
      end
    end
  end

  def self.down
  end
end
